# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
variables:
  imageName: patrickfxyz-hugo
  version: 0.0.1
 
trigger:
- master
# update triggers to build based on branch/?? and/or certain changes

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_10_16:
      node_version: '10.16'
  maxParallel: 1

steps:
- task: Docker@2
  displayName: Build an hugo Docker image
  inputs:
    command: buildAndPush
    repository: patrickfxyz/$(imageName)
    dockerfile: Dockerfile-hugo
    containerRegistry: AzurecontainerRegistry
    tags: |
      $(version)
