FROM golang:1.13.3-alpine3.10

LABEL description="Docker container for building patrickf.xyz static site with the Hugo static site generator."
LABEL maintainer="Patrick Freeman" 

RUN apk add --update git curl asciidoctor openssh-client rsync libc6-compat libstdc++ \
    && apk upgrade \
    && apk add --no-cache ca-certificates

ARG VERSION=0.59.1

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz hugo_${VERSION}_Linux-64bit.tar.gz

RUN tar -zxvf hugo_${VERSION}_Linux-64bit.tar.gz

RUN mv hugo /usr/local/bin/hugo 

RUN /usr/local/bin/hugo version
    
RUN mkdir -p /app

RUN pwd

WORKDIR /app/patrickf-hugo

RUN pwd

COPY patrickf-hugo /app/patrickf-hugo/

RUN ls -lart *

RUN /usr/local/bin/hugo