FROM alpine:latest

MAINTAINER Patrick Freeman

RUN apk add --no-cache \
    curl \
    git \
    openssh-client \
    rsync

ENV VERSION 0.59.1
RUN mkdir -p /usr/local/src \
    && cd /usr/local/src \

    && curl -L https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_linux-64bit.tar.gz | tar -xz \
    && mv hugo /usr/local/bin/hugo \

    && curl -L https://bin.equinox.io/c/dhgbqpS8Bvy/minify-stable-linux-amd64.tgz | tar -xz \
    && mv minify /usr/local/bin/ \

    && addgroup -Sg 1000 hugo \
    && adduser -SG hugo -u 1000 -h /src hugo

RUN mkdir -p /src/patrickf-hugo

WORKDIR /src

COPY patrickf-hugo/ /src/patrickf-hugo

COPY patrickf-hugo/themes/KeepIT /src/patrickf-hugo/themes/KeepIT 

RUN ls -lart *

WORKDIR /src/patrickf-hugo