FROM golang:1.13.3-alpine3.10

MAINTAINER Patrick Freeman

RUN apk add --no-cache \
    curl \
    git \
    openssh-client \
    rsync

ARG VERSION=0.59.1

ADD https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz hugo_${VERSION}_Linux-64bit.tar.gz

RUN tar -zxvf hugo_${VERSION}_Linux-64bit.tar.gz

RUN mv hugo /usr/local/bin/hugo 

RUN /usr/local/bin/hugo version
    
RUN mkdir -p /app/patrickf-hugo

WORKDIR /app

COPY patrickf-hugo /app/patrickf-hugo

RUN ls -lart *

WORKDIR /app/patrickf-hugo

RUN /usr/local/bin/hugo