FROM node:10.16.3-alpine

# js vars
ENV PATH /app/patrickf-ui/node_modules/.bin:$PATH

# react build
RUN mkdir -p /app/patrickf-ui
WORKDIR /app
COPY patrickf-ui /app/patrickf-ui
WORKDIR /app/patrickf-ui
RUN npm install --silent
RUN npm install react -g --silent
RUN npm install react-scripts -g --silent
RUN npm run build