---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrickfxyz-hugo-deployment
  labels:
    app: patrickfxyz-hugo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patrickfxyz-hugo
  template:
    metadata:
      labels:
        app: patrickfxyz-hugo
    spec:
      containers:
      - name: patrickfxyz-hugo
        image: patrickfRegistry.azurecr.io/patrickfxyz/patrickfxyz-hugo:0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - /usr/local/bin/hugo server -D --config /app/patrickf-hugo/config.toml --theme /app/patrickf-hugo/themes/KeepIT  -p 3000 --disableLiveReload;
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acrsecret1
