---
kind: Service
apiVersion: v1
metadata:
  name: patrickfxyz-dolb-nginx-https
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "35616d08-3445-4610-abeb-765b9c966ad2"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: patrickfxyz-hugo
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000