---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app: nginx-patrickfxyz
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app: nginx-patrickfxyz
    spec:
      containers:
      - name: nginx-patrickfxyz
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: https-with-cert-minimal
  annotations:
    # No TLS port annotation needed since 443 is assumed for HTTPS when another TLS option annotation is given.
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "35616d08-3445-4610-abeb-765b9c966ad2"
spec:
  type: LoadBalancer
  selector:
    app: nginx-patrickfxyz
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

### replace patrickfxyz with APP VAR
### replace cert id with VAR

#Note: add config map and nginx conf. Remove nginx versions, redirect unsecure to secure, etc...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nginx.conf: |
user nginx;
worker_processes auto;
error_log /app/logs/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /app/logs/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    server_tokens off;

upstream rancher {
    server {{ansible_fqdn}}:8080;
}

map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
    listen 443 ssl spdy;
    server_name {{ansible_fqdn}};
    ssl_certificate /app/ssl/certs/{{ansible_fqdn}}.crt;
    ssl_certificate_key /app/ssl/private/{{ansible_fqdn}}.key;

    access_log /app/logs/nginx/{{ansible_fqdn}}.log;
    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name {{ansible_fqdn}};
    return 301 https://{{ansible_fqdn}}$request_uri;
}


}
