---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrickfxyz-django-deployment
  labels:
    app: patrickfxyz-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patrickfxyz-django
  template:
    metadata:
      labels:
        app: patrickfxyz-django
    spec:
      containers:
      - name: patrickfxyz-django
        image: patrickfRegistry.azurecr.io/patrickfxyz/patrickfxyz-django:0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - python3 manage.py migrate --noinput; python3 manage.py runserver 0.0.0.0:8000;
        ports:
        - containerPort: 8000
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: user
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: password
        - name: DBSECRETKEY
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: secretkey
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: dbname
        - name: DBPORT
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: dbport
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: patrickfxyz-creds
              key: dbendpoint
        - name: DEBUGLOG
          value: 'TRUE'
      imagePullSecrets:
      - name: acrsecret1
