---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patrickf-djagno-backend-config
data:
  DB_HOST: {{ .Values.DBHOST }} #e.g. postgres
  DB_NAME: {{ .Values.DBNAME }}
  DB_USER: {{ .Values.DBUSER }}
  DB_PASS: {{ .Values.DBPASS }}
  DB_PORT: {{ .Values.DBPORT }}
  DB_SECRETKEY: {{ .Values.DBSECRETKEY }}
  DEBUGLOG: {{ .Values.DEBUGLOG }}

apiVersion: batch/v1
kind: Job
metadata:
  name: patrickfxyz/patrickfxyz-django-react-migrate
  labels:
    name: django-k8s-starter
    type: migrate
spec:
  template:
    spec:
      containers:
      - name: patrickfxyz/patrickfxyz-django-react-migrate
        image: patrickfregistry.azurecr.io/patrickfxyz/patrickfxyz-django-react:0.0.1
        command: ["python",  "manage.py", "migrate", "--noinput"]
        envFrom:
        - configMapRef:
            name: patrickfxyz-django-react-config
      restartPolicy: Never
  backoffLimit: 4