---
apiVersion: v1
kind: Service
metadata:
  name: patrickf-progresql
  labels:
    app: drupal
spec:
  ports:
    - port: 5432
  selector:
    app: patrickf-progresql
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patrickf-progresql-claim
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: patrickf-progresql
  labels:
    app: patrickf-progresql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: patrickf-progresql
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:latest
          name: patrickf-progresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: patrickfxyz
            - name: POSTGRES_PASSWORD
              value: password123
          ports:
            - containerPort: 5432
              name: patrickf-progresql
          volumeMounts:
            - name: patrickf-progresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: patrickf-progresql
          persistentVolumeClaim:
            claimName: patrickf-progresql-claim